In [5]:
import numpy as np

# A是array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
A = np.arange(18)

# 将A变换为三维矩阵
A = A.reshape(2,1,3,3)
print(A)

A = A.transpose((0,3,2,1))
print(A)


[[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]]]


 [[[ 9 10 11]
   [12 13 14]
   [15 16 17]]]]
[[[[ 0]
   [ 3]
   [ 6]]

  [[ 1]
   [ 4]
   [ 7]]

  [[ 2]
   [ 5]
   [ 8]]]


 [[[ 9]
   [12]
   [15]]

  [[10]
   [13]
   [16]]

  [[11]
   [14]
   [17]]]]
